name = "wxchat-pages"
compatibility_date = "2025-06-17"

# Pages 配置
pages_build_output_dir = "./public"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "wxchat"
database_id = "b58dde57-d777-459f-a6b3-ae4de9c16368"

# R2 存储桶绑定
[[r2_buckets]]
binding = "R2"
bucket_name = "wxchat"

# 环境变量配置
[vars]
ENVIRONMENT = "production"
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin123"